# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hanlp_pb2 as hanlp__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.segment = channel.unary_unary(
        '/helloworld.Greeter/segment',
        request_serializer=hanlp__pb2.HanlpRequest.SerializeToString,
        response_deserializer=hanlp__pb2.HanlpReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def segment(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'segment': grpc.unary_unary_rpc_method_handler(
          servicer.segment,
          request_deserializer=hanlp__pb2.HanlpRequest.FromString,
          response_serializer=hanlp__pb2.HanlpReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'helloworld.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
