# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hanlp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hanlp.proto',
  package='helloworld',
  syntax='proto3',
  serialized_pb=_b('\n\x0bhanlp.proto\x12\nhelloworld\"\xd4\x01\n\x0cHanlpRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x11\n\tindexMode\x18\x02 \x01(\x08\x12\x15\n\rnameRecognize\x18\x03 \x01(\x08\x12\x1f\n\x17translatedNameRecognize\x18\x04 \x01(\x08\x12\x1d\n\x15japaneseNameRecognize\x18\x05 \x01(\x08\x12\x16\n\x0eplaceRecognize\x18\x06 \x01(\x08\x12\x1d\n\x15organizationRecognize\x18\x07 \x01(\x08\x12\x15\n\rspeechTagging\x18\x08 \x01(\x08\"I\n\nHanlpReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\x1e\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32\x10.helloworld.Term\"E\n\x04Term\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x11\n\tattribute\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\x0c\n\x04info\x18\x04 \x01(\t2H\n\x07Greeter\x12=\n\x07segment\x12\x18.helloworld.HanlpRequest\x1a\x16.helloworld.HanlpReply\"\x00\x42\'\n\x11io.grpc.abc.hanlpB\nHanlpProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_HANLPREQUEST = _descriptor.Descriptor(
  name='HanlpRequest',
  full_name='helloworld.HanlpRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='helloworld.HanlpRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='indexMode', full_name='helloworld.HanlpRequest.indexMode', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nameRecognize', full_name='helloworld.HanlpRequest.nameRecognize', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translatedNameRecognize', full_name='helloworld.HanlpRequest.translatedNameRecognize', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='japaneseNameRecognize', full_name='helloworld.HanlpRequest.japaneseNameRecognize', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='placeRecognize', full_name='helloworld.HanlpRequest.placeRecognize', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='organizationRecognize', full_name='helloworld.HanlpRequest.organizationRecognize', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speechTagging', full_name='helloworld.HanlpRequest.speechTagging', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=240,
)


_HANLPREPLY = _descriptor.Descriptor(
  name='HanlpReply',
  full_name='helloworld.HanlpReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='helloworld.HanlpReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='helloworld.HanlpReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='helloworld.HanlpReply.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=315,
)


_TERM = _descriptor.Descriptor(
  name='Term',
  full_name='helloworld.Term',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='helloworld.Term.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='helloworld.Term.attribute', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='helloworld.Term.offset', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='helloworld.Term.info', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=386,
)

_HANLPREPLY.fields_by_name['data'].message_type = _TERM
DESCRIPTOR.message_types_by_name['HanlpRequest'] = _HANLPREQUEST
DESCRIPTOR.message_types_by_name['HanlpReply'] = _HANLPREPLY
DESCRIPTOR.message_types_by_name['Term'] = _TERM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HanlpRequest = _reflection.GeneratedProtocolMessageType('HanlpRequest', (_message.Message,), dict(
  DESCRIPTOR = _HANLPREQUEST,
  __module__ = 'hanlp_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HanlpRequest)
  ))
_sym_db.RegisterMessage(HanlpRequest)

HanlpReply = _reflection.GeneratedProtocolMessageType('HanlpReply', (_message.Message,), dict(
  DESCRIPTOR = _HANLPREPLY,
  __module__ = 'hanlp_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.HanlpReply)
  ))
_sym_db.RegisterMessage(HanlpReply)

Term = _reflection.GeneratedProtocolMessageType('Term', (_message.Message,), dict(
  DESCRIPTOR = _TERM,
  __module__ = 'hanlp_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.Term)
  ))
_sym_db.RegisterMessage(Term)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021io.grpc.abc.hanlpB\nHanlpProtoP\001\242\002\003HLW'))

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='helloworld.Greeter',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=388,
  serialized_end=460,
  methods=[
  _descriptor.MethodDescriptor(
    name='segment',
    full_name='helloworld.Greeter.segment',
    index=0,
    containing_service=None,
    input_type=_HANLPREQUEST,
    output_type=_HANLPREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
